packageExtensions:
  react-intl@*:
    dependencies:
      '@formatjs/ecma402-abstract': '*'
  '@formatjs/intl@*':
    dependencies:
      '@formatjs/icu-messageformat-parser': '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@atls/plugin-essentials.js

yarnPath: .yarn/releases/yarn-3.0.0-rc.5.cjs
